<?php

namespace Projet2\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function loadItem() {
        $result = $this ->createQueryBuilder('i')
                        ->select('i')
                        ->orderBy('i.category')
                        ->getQuery()
                        ->getResult();
        return $result;
    }
}
