<?php

namespace Projet2\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersItemRepository extends EntityRepository
{
}
