<?php

namespace Projet2\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    /**
     * Affiche la liste des commandes d'un utilisateur
     */
    public function loadOrders($id) {
        
        $result = $this ->createQueryBuilder('o')
                        ->select('o')
                        ->where('o.userId = :userId')
                        ->setParameter('userId', $id)
                        ->getQuery()
                        ->getResult();
        return $result;
    }
}
