front_index:
    resource:  '@FrontBundle/Controller/IndexController.php'
    type: annotation

front_item:
    resource:  '@FrontBundle/Controller/ItemController.php'
    type: annotation

front_user:
    resource:  '@FrontBundle/Controller/UserController.php'
    type: annotation

front_cart:
    resource:  '@FrontBundle/Controller/CartController.php'
    type: annotation

front_orders:
    resource:  '@FrontBundle/Controller/OrdersController.php'
    type: annotation