back_admin:
    resource:  '@BackBundle/Controller/AdminController.php'
    type: annotation

login:
     pattern:   /login
     defaults:  { _controller: BackBundle:Security:login }

login_check:
      pattern:   /login_check

logout:
      pattern:   /logout
      